#define ETH_PRIVATE_KEY_BIN_LEN 32
#define ETH_PRIVATE_KEY_HEX_LEN ETH_PRIVATE_KEY_BIN_LEN * 2

#define ETH_PUBLIC_KEY_BIN_LEN 65
#define ETH_PUBLIC_KEY_HEX_LEN ETH_PUBLIC_KEY_BIN_LEN * 2

#define ETH_PUBLIC_KEY_COMPRESSED_BIN_LEN 33
#define ETH_PUBLIC_KEY_COMPRESSED_HEX_LEN ETH_PUBLIC_KEY_COMPRESSED_BIN_LEN * 2

#define ETH_ADDRESS_BIN_LEN 20
#define ETH_ADDRESS_HEX_LEN ETH_ADDRESS_BIN_LEN * 2

#define KECCAK_BIN_LEN 32
#define KECCAK_HEX_LEN KECCAK_BIN_LEN * 2
